server:
  port: 9100

spring:
  application:
    name: app-eureka1
  security:
    basic:
      enable: true #HTTP basic
    user: 
      name: wjw
      password: 123456
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:9100/eureka/
    register-with-eureka: false
    fetch-registry: true